### ISSUE TITLE
Source code of kernel

### ISSUE THREAD

**Issue by mahadeva604** [Spitzbube/hisilicon-kernel#1]
Hi. Iconbit company (Russia) share of kernel source code for device based on hi3798mx chip. You can get it here https://yadi.sk/d/itFKKY9QjshXY .

**Comment by Spitzbube** [comment]
Thanks for this information! I have taken a look at it and I already found some useful infos. But what I am more interested in are the drivers for for hw components of the hi3798 soc. I have got already parts of the HiSTBLinuxV100R003C00SPC053 and HiSTBLinuxV100R003C00SPC055 packages but there are many things missing...

**Comment by Spitzbube** [comment]
Thanks for this information! I have taken a look at it and I already found
some useful infos. But what I am more interested in are the drivers for the
hw components of the hi3798 soc. I have got already parts of the
HiSTBLinuxV100R003C00SPC053 and HiSTBLinuxV100R003C00SPC055 packages but
there are many things missing...

I would like to port OpenELEC to my box Himedia Q5 4k3d. At the moment I am
running the original Android kernel but with an Linaro Nano rootfs (without
graphical UI). Step by step I try to enable the Hisilicon user mode
libraries and the sample applications.

 Regards,

Spitzbube

----- Цитат от Alexander Lozovoi (notifications@github.com), на
21.10.2015 в 12:53 -----  

Hi. Iconbit company (Russia) share of kernel source code for device based
on hi3798mx chip. You can get it here https://yadi.sk/d/itFKKY9QjshXY [1] .

—
Reply to this email directly or view it on GitHub [2].  
    \*      

## Links:

[1] https://yadi.sk/d/itFKKY9QjshXY
[2] https://github.com/Spitzbube/hisilicon-kernel/issues/1

---

Mail.BG: Безплатен e-mail адрес. Най-добрите характеристики на българския пазар - 20 GB пощенска кутия, 1 GB прикрепен файл, безплатен POP3, мобилна версия, SMS известяване и други. http://mail.bg

**Comment by mahadeva604** [comment]
Very interesting. Good luck with work.

**Comment by Spitzbube** [comment]
Hi3798mx kernel is available with https://github.com/Spitzbube/hisilicon-kernel/commit/b4e1b4afa0d52cb84d650cd44caa123323d353f0
